export const TOKEN_FETCH = 'TOKEN_FETCH';

export const LOGIN_CREATE = 'LOGIN_CREATE';
export const LOGIN_CREATE_REQUEST = 'LOGIN_CREATE_REQUEST';
export const LOGIN_CREATE_SUCCESS = 'LOGIN_CREATE_SUCCESS';
export const LOGIN_CREATE_ERROR = 'LOGIN_CREATE_ERROR';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';

export const USER_FETCH = 'USER_FETCH';
export const USER_FETCH_REQUEST = 'USER_FETCH_REQUEST';
export const USER_FETCH_SUCCESS = 'USER_FETCH_SUCCESS';
export const USER_FETCH_ERROR = 'USER_FETCH_ERROR';

export const STUDENTS_FETCH = 'STUDENTS_FETCH';
export const STUDENTS_FETCH_REQUEST = 'STUDENTS_FETCH_REQUEST';
export const STUDENTS_FETCH_SUCCESS = 'STUDENTS_FETCH_SUCCESS';
export const STUDENTS_FETCH_ERROR = 'STUDENTS_FETCH_ERROR';

export const STUDENTS_FILE_UPLOAD = 'STUDENTS_FILE_UPLOAD';
export const STUDENTS_FILE_UPLOAD_REQUEST = 'STUDENTS_FILE_UPLOAD_REQUEST';
export const STUDENTS_FILE_UPLOAD_SUCCESS = 'STUDENTS_FILE_UPLOAD_SUCCESS';
export const STUDENTS_FILE_UPLOAD_ERROR = 'STUDENTS_FILE_UPLOAD_ERROR';

export const BEHAVIOUR_CATEGORY_FETCH = 'BEHAVIOUR_CATEGORY_FETCH';
export const BEHAVIOUR_CATEGORY_FETCH_REQUEST = 'BEHAVIOUR_CATEGORY_FETCH_REQUEST';
export const BEHAVIOUR_CATEGORY_FETCH_SUCCESS = 'BEHAVIOUR_CATEGORY_FETCH_SUCCESS';
export const BEHAVIOUR_CATEGORY_FETCH_ERROR = 'BEHAVIOUR_CATEGORY_FETCH_ERROR';

export const BEHAVIOUR_CATEGORY_CREATE = 'BEHAVIOUR_CATEGORY_CREATE';
export const BEHAVIOUR_CATEGORY_CREATE_REQUEST = 'BEHAVIOUR_CATEGORY_CREATE_REQUEST';
export const BEHAVIOUR_CATEGORY_CREATE_SUCCESS = 'BEHAVIOUR_CATEGORY_CREATE_SUCCESS';
export const BEHAVIOUR_CATEGORY_CREATE_ERROR = 'BEHAVIOUR_CATEGORY_CREATE_ERROR';

export const BEHAVIOUR_CATEGORY_UPDATE = 'BEHAVIOUR_CATEGORY_UPDATE';
export const BEHAVIOUR_CATEGORY_UPDATE_REQUEST = 'BEHAVIOUR_CATEGORY_UPDATE_REQUEST';
export const BEHAVIOUR_CATEGORY_UPDATE_SUCCESS = 'BEHAVIOUR_CATEGORY_UPDATE_SUCCESS';
export const BEHAVIOUR_CATEGORY_UPDATE_ERROR = 'BEHAVIOUR_CATEGORY_UPDATE_ERROR';

export const BEHAVIOUR_CATEGORY_DELETE = 'BEHAVIOUR_CATEGORY_DELETE';
export const BEHAVIOUR_CATEGORY_DELETE_REQUEST = 'BEHAVIOUR_CATEGORY_DELETE_REQUEST';
export const BEHAVIOUR_CATEGORY_DELETE_SUCCESS = 'BEHAVIOUR_CATEGORY_DELETE_SUCCESS';
export const BEHAVIOUR_CATEGORY_DELETE_ERROR = 'BEHAVIOUR_CATEGORY_DELETE_ERROR';

export const BEHAVIOUR_FETCH = 'BEHAVIOUR_FETCH';
export const BEHAVIOUR_FETCH_REQUEST = 'BEHAVIOUR_FETCH_REQUEST';
export const BEHAVIOUR_FETCH_SUCCESS = 'BEHAVIOUR_FETCH_SUCCESS';
export const BEHAVIOUR_FETCH_ERROR = 'BEHAVIOUR_FETCH_ERROR';

export const BEHAVIOUR_CREATE = 'BEHAVIOUR_CREATE';
export const BEHAVIOUR_CREATE_REQUEST = 'BEHAVIOUR_CREATE_REQUEST';
export const BEHAVIOUR_CREATE_SUCCESS = 'BEHAVIOUR_CREATE_SUCCESS';
export const BEHAVIOUR_CREATE_ERROR = 'BEHAVIOUR_CREATE_ERROR';

export const BEHAVIOUR_UPDATE = 'BEHAVIOUR_UPDATE';
export const BEHAVIOUR_UPDATE_REQUEST = 'BEHAVIOUR_UPDATE_REQUEST';
export const BEHAVIOUR_UPDATE_SUCCESS = 'BEHAVIOUR_UPDATE_SUCCESS';
export const BEHAVIOUR_UPDATE_ERROR = 'BEHAVIOUR_UPDATE_ERROR';

export const BEHAVIOUR_DELETE = 'BEHAVIOUR_DELETE';
export const BEHAVIOUR_DELETE_REQUEST = 'BEHAVIOUR_DELETE_REQUEST';
export const BEHAVIOUR_DELETE_SUCCESS = 'BEHAVIOUR_DELETE_SUCCESS';
export const BEHAVIOUR_DELETE_ERROR = 'BEHAVIOUR_DELETE_ERROR';

export const OBSERVATION_FETCH = 'OBSERVATION_FETCH';
export const OBSERVATION_FETCH_REQUEST = 'OBSERVATION_FETCH_REQUEST';
export const OBSERVATION_FETCH_SUCCESS = 'OBSERVATION_FETCH_SUCCESS';
export const OBSERVATION_FETCH_ERROR = 'OBSERVATION_FETCH_ERROR';

export const OBSERVATION_CREATE = 'OBSERVATION_CREATE';
export const OBSERVATION_CREATE_REQUEST = 'OBSERVATION_CREATE_REQUEST';
export const OBSERVATION_CREATE_SUCCESS = 'OBSERVATION_CREATE_SUCCESS';
export const OBSERVATION_CREATE_ERROR = 'OBSERVATION_CREATE_ERROR';

export const REPORT_FETCH = 'REPORT_FETCH';
export const REPORT_FETCH_REQUEST = 'REPORT_FETCH_REQUEST';
export const REPORT_FETCH_SUCCESS = 'REPORT_FETCH_SUCCESS';
export const REPORT_FETCH_ERROR = 'REPORT_FETCH_ERROR';

export const INVITES_FETCH = 'INVITES_FETCH';
export const INVITES_FETCH_REQUEST = 'INVITES_FETCH_REQUEST';
export const INVITES_FETCH_SUCCESS = 'INVITES_FETCH_SUCCESS';
export const INVITES_FETCH_ERROR = 'INVITES_FETCH_ERROR';

export const INVITE_CREATE = 'INVITE_CREATE';
export const INVITE_CREATE_REQUEST = 'INVITE_CREATE_REQUEST';
export const INVITE_CREATE_SUCCESS = 'INVITE_CREATE_SUCCESS';
export const INVITE_CREATE_ERROR = 'INVITE_CREATE_ERROR';